version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres_usuario:
    image: postgres:17
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: usuario_db
    ports:
      - "5434:5432"

  postgres_resena:
    image: postgres:17
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: resena_db
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
